service: serverless-cognito

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

resources:
  Resources:
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        Schema:
          - Name: "email"
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
            Required: true
            AttributeDataType: "String"
            Mutable: true
        AliasAttributes: ["email"]
        AutoVerifiedAttributes: ["email"]
        EmailVerificationSubject: "Your verification code"
        EmailVerificationMessage: "Your confirmation code is {####}."
        MfaConfiguration: "OFF"
        UserPoolName:
          Ref: AWS::StackName
        Policies:
          PasswordPolicy:
            RequireLowercase: false
            RequireSymbols: false
            RequireNumbers: true 
            MinimumLength: 6
            RequireUppercase: false
    UserPoolClient:
      Type: "AWS::Cognito::UserPoolClient"
      Properties:
        ClientName:
          Ref: AWS::StackName
        GenerateSecret: false
        UserPoolId:
          Ref: UserPool
    UserIdentityPool:
      Type: "AWS::Cognito::IdentityPool"
      Properties:
        IdentityPoolName: MyIdentityPool
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId:
              Ref: UserPoolClient
            ProviderName:
              Fn::Join:
                - ""
                - - cognito-idp.
                  - Ref: "AWS::Region"
                  - .amazonaws.com/
                  - Ref: UserPool
            ServerSideTokenCheck: false
  Outputs:
    UserPoolId:
      Description: 'The name of the user pool'
      Value:
        Ref: UserPool
    UserPoolClientId:
      Description: 'The name of the user pool client'
      Value:
        Ref: UserPoolClient
    MyIdentityPool:
      Description: 'Identity Pool ID'
      Value:
        Ref: UserIdentityPool
