service: serverless-api

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

custom:
  cognitoStackName: serverless-cognito
  cognitoCfName: ${self:custom.cognitoStackName}-dev

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: demo/index
          method: get
          authorizer:
            arn: "arn:aws:cognito-idp:${self:provider.region}:#{AWS::AccountId}:userpool/${cf:serverless-cognito-dev.UserPoolId}"
          cors: true